"""new tables for image and classification

Revision ID: 309c410ebe61
Revises: 369ce8eefb0d
Create Date: 2025-04-16 03:00:31.721958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309c410ebe61'
down_revision: Union[str, None] = '369ce8eefb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classificacao', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('dtcadastro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dtnascimento_paciente', sa.Date(), nullable=False),
    sa.Column('dtprocedimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imagem_full_path', sa.String(length=524), nullable=False),
    sa.Column('classificacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classificacao_id'], ['classificacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagem')
    op.drop_table('classificacao')
    # ### end Alembic commands ###
