"""add dtcriado column to user and now some columns can be null

Revision ID: 369ce8eefb0d
Revises: 7effac5fcb30
Create Date: 2025-04-14 02:41:18.956574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '369ce8eefb0d'
down_revision: Union[str, None] = '7effac5fcb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('dtcriado', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('usuario', 'matricula',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usuario', 'curso',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'curso',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('usuario', 'matricula',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('usuario', 'dtcriado')
    # ### end Alembic commands ###
