"""add: usuario column

Revision ID: 462e93efe488
Revises: 6362e9607723
Create Date: 2025-04-08 11:57:18.596503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462e93efe488'
down_revision: Union[str, None] = '6362e9607723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('usuario', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'usuario', ['usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'usuario')
    # ### end Alembic commands ###
