"""add 'administrador' column to user

Revision ID: 53f2d73495d4
Revises: 309c410ebe61
Create Date: 2025-04-16 19:25:19.499434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f2d73495d4'
down_revision: Union[str, None] = '309c410ebe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('administrador', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'administrador')
    # ### end Alembic commands ###
