"""add email to user model

Revision ID: 7effac5fcb30
Revises: 462e93efe488
Create Date: 2025-04-14 02:36:08.308470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7effac5fcb30'
down_revision: Union[str, None] = '462e93efe488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.String(length=180), nullable=False))
    op.create_unique_constraint(None, 'usuario', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###
